"use strict";
import React from "react";
import localFont from "next/font/local";
import "./globals.css";
// import SkipNavLink from "react-skip-nav";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});

const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata = {
    title: "freeonlinemarketplace.com - Home",
    description: "Generated by create next app",
};

// async function getAllItemsFromStore() {
//     const db = await openDB("test-db4", 1);

//     // Get all values from the designated object store:
//     const allValues = await db.getAll("storeName");

//     console.dir(allValues);
// }

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${
                    geistSans.className
                } antialiased selection:subpixel-antialiased selection:bg-[#88ffff] selection:text-[#0d0d0d] overflow-x-clip relative min-h-[100vh]
                !debug
                `}
            >
                {/* <a href="#main-content" className="skip-navigation">
                    Skip to main content
                </a> */}
                {/* <div
                    id="g_id_onload"
                    data-client_id="124948975712-u4lkoqbp0a4oucic5cf9dk916gbs6878.apps.googleusercontent.com"
                    data-login_uri="https://your.domain/your_login_endpoint"
                    data-your_own_param_1_to_login="any_value"
                    data-your_own_param_2_to_login="any_value"
                ></div> */}
                {/* <div className="relative z-[100]"> */}
                {/* <SkipNavLink>Accessibility feedback</SkipNavLink> */}
                {/* </div> */}
                {children}
            </body>
        </html>
    );
}
